### ISSUE TITLE
Don't support whitespace in tag name

### ISSUE THREAD

**Issue by raysegantii** [deadmanssnitch/snitcher#15]
1. Create a tag with whitespace, e.g. "hellow world"
1. `client.tagged_snitches(["hello world"])`

Failed with: `TypeError: no implicit conversion of String into Integer`

**Comment by gaffneyc** [comment]
@raysegantii Thank you for the bug report. We'll get it figured out in the next day or two.

**Comment by gaffneyc** [comment]
@raysegantii Quick note to let you know that we now support passing multiple tags without wrapping them in an array. 

So both of these work now:
`client.tagged_snitches(["hello world", "world hello"])`
and
`client.tagged_snitches("hello world", "world hello")`

**Comment by raysegantii** [comment]
@gaffneyc Great one, thank you!
