### ISSUE TITLE
Incorrect API key causes nondescript error

### ISSUE THREAD

**Issue by jcross-linkup** [deadmanssnitch/snitcher#16]
Thanks for providing a prebuilt Ruby gem for interacting with DMS.  I used it to parse some meta data I added to our crontab to automatically add 91 cron jobs in one go.  We're pretty happy with it all so far.  I did run into a small problem that would probably be worth fixing for future users.

Instead of raising an exception, the following code bombs out if an incorrect API key is used:
```ruby
require 'snitcher/api'
client = Snitcher::API::Client.new(api_key: "INCORRECTKEY")

# the next line fails
snitches = client.snitches
```
The error is:
```
/home/jcross/.gem/ruby/gems/snitcher-0.3.2/lib/snitcher/api/snitch.rb:34:in `[]': no implicit conversion of String into Integer (TypeError)
	from /home/jcross/.gem/ruby/gems/snitcher-0.3.2/lib/snitcher/api/snitch.rb:34:in `initialize'
	from /home/jcross/.gem/ruby/gems/snitcher-0.3.2/lib/snitcher/api/client.rb:294:in `new'
	from /home/jcross/.gem/ruby/gems/snitcher-0.3.2/lib/snitcher/api/client.rb:294:in `block in snitch_array'
	from /home/jcross/.gem/ruby/gems/snitcher-0.3.2/lib/snitcher/api/client.rb:292:in `each'
	from /home/jcross/.gem/ruby/gems/snitcher-0.3.2/lib/snitcher/api/client.rb:292:in `snitch_array'
	from /home/jcross/.gem/ruby/gems/snitcher-0.3.2/lib/snitcher/api/client.rb:49:in `snitches'
	from add_tags.rb:5:in `<main>'
```
The payload passed into the snitch initializer is:
```
[:message, "Response unsuccessful"]
```
It would be helpful if an exception was thrown with a message of something along the lines of "Access Denied for API Key."

**Comment by gaffneyc** [comment]
@jcross-linkup Thanks for the bug report. We're still working on the API integration so the client API is still up in the air a bit. I'll be taking a look at this in the next day or two and getting a fix out there.

**Comment by gaffneyc** [comment]
This now throws a `Snitcher::API::AuthenticationError` on first use of the API after creating the client.

```ruby
> client = Snitcher::API::Client.new("laksjdal;ksjd")
> client.snitches
Snitcher::API::AuthenticationError: Access denied. Provide your API Key as the user for HTTP Basic Authentication.
```
