### ISSUE TITLE
api docs missing fields

### ISSUE THREAD

**Issue by andreaspe** [deadmanssnitch/snitcher#25]
tiny issue: the API documentation at https://deadmanssnitch.com/docs/api/v1#creating-a-snitch does not mention the  'alert_email' field.

**Comment by hvisage** [comment]
and it's also not "Exposed" through  the API, so I can't check etc. all the snitches where we must changes etc.

**Comment by gaffneyc** [comment]
We've officially added `alert_email` to the API so it's now [documented](https://deadmanssnitch.com/docs/api/v1) and included in the response.
